# Generated by Django 5.0 on 2023-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('BASIC', 'Free plan'), ('Premium', 'Paid plan')], default='BASIC', max_length=10),
        ),
    ]
