# Generated by Django 5.0 on 2023-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_customer_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='feature_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
