# Generated by Django 5.0 on 2023-12-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_collection_feature_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='feature_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
